### PR TITLE
Added Elan Enterprise and Videoton TVC official and user fonts

### PR DESCRIPTION
**Pull request by SlashNetUA**
Elan Enterprise: https://en.wikipedia.org/wiki/Enterprise_(computer)
Videoton TVC: https://en.wikipedia.org/wiki/Videoton_TV-Computer

### CODE REVIEW

**Comment by robhagemans** [comment]
Thanks! Out of interest, you mentioned in the comments they were
'recreated', how did you create/extract them?

**Comment by SlashNetUA** [comment]
I did it using an ordinary text editor.
At first I tried to convert the font from the edited screenshot from the emulator, but I couldn't get monobit to create characters 9 pixels high and above (it stubbornly generated characters 8 pixels high).

**Comment by robhagemans** [comment]
All done manually sounds like a lot of work! Which emulator did you use for
the screenshot?

Apologies monobit documentation is still very sparse, there is a -cell-size
option that should allow to set 9x8 character sizes when reading an image.
Try `monobit-convert --help -format=image` for all the options (or check
the source code at `monobit/formats/image.py` )

**Comment by SlashNetUA** [comment]
> All done manually sounds like a lot of work! Which emulator did you use for the screenshot? 

Not so much. 🙂
I love pixel fonts, too. I started making them back on my Enterprise (since it was easy enough).
Then when I got my IBM PC-compatible computer I made my first font for text mode (.fnt) with the hex editor. 🤪

Nowadays I sometimes help enthusiastic translators create Cyrillic versions of pixel fonts for old games.

To emulate Enterprise (and some other machines on the Z80 processor) I mostly use the multisystem emulator ep128emu (https://sourceforge.net/projects/ep128emu/).

**Pull request merged**
