### PR TITLE
Datapoint 8600

### PR DESCRIPTION
**Pull request by Mecrisp**

### CODE REVIEW

**Comment by robhagemans** [comment]
Thanks for this! One thing - I generally do not store the ROM dumps themselves in this repo, so I'll probably take only the first commit. Though we can do a README with links to the originals?

**Comment by Mecrisp** [comment]
Sure, fine!
The originals are in an E-Mail of the museum crew to me. I just copied these to my own homepage. In a minute, you'll get a readme file.

**Comment by Mecrisp** [comment]
Done! The last commit contains the Readme, had to try three times to get links right.

**Comment by robhagemans** [comment]
Thanks! I've merged a rebased version manually. There were a few more housekeeping items (I resized and moved the images) and it was easier this way.

**Pull request closed without merging**
