### PR TITLE
Videowriter250

### PR DESCRIPTION
**Pull request by robcfg**
This is the font of the VideoWriter 250 (https://en.wikipedia.org/wiki/VideoWriter), which was part of a range of dedicated word processing machines made by Philips.

These machines use the NCR7250 video chip, so to extract the font, a donated chip was sent for decapping and the font assembled from the rom pictures. 

The VideoWriter 250 use the arabic attribute for some characters allowing the display of wide characters without any artifacts like a vertical line between them.

The font file contains normal and inverse video characters.

Best regards,
Rob

### CODE REVIEW

**Comment by robhagemans** [comment]
Thanks! I might move this to the ncr7250 directory later given that it used that chipset - I haven't quite worked out what is the best way to organise this collection...

**Comment by robhagemans** [comment]
There's something weird going on in the higher codepoints - it looks like these are ither stretched horizontally or meant to be wider characters that somehow got cropped. Is that how it is meant to look?

As an aside, comments in `yaff` files should be on lines starting with Python-style `#` rather than C++-style `//`, but I can fix that later.

**Comment by robcfg** [comment]
Yes, they are meant to be wider characters, so you have to use two halves
to get a full wide character.

As I mentioned, the font is 8x12 in rom, but the chip duplicates the first
column or copies to the first column after the last one.

I’m working on having the machine emulated in Mame and know this font to be
accurate.

Thanks for pointing me to the comments error!

Best regards,
Rob

**Comment by robcfg** [comment]
> Thanks! I might move this to the ncr7250 directory later given that it used that chipset - I haven't quite worked out what is the best way to organise this collection...

There are a bunch of Philips machines, and a may have access to some of them soon, so I think the VideoWriter 250 is on the right place.

If you don't like having a folder for just a file, maybe you could move the NCR7250 one to a misc or mixed folder.

Cheers,
Rob

**Pull request merged**
